### ISSUE TITLE
vgmplay not running fine from caja/nautilus script

### ISSUE THREAD

**Issue by nitrofurano** [vgmrips/vgmplay#25]
when i try to run vgmplay from caja/nautilus script (context menu over a vgm file in the file manager), it asks for the filename, when it was supposed to start playing automatically

below is the script i have at ~/.config/caja/scripts/ : 
```
#!/bin/bash
filesall=""
while [ $# -gt 0 ]
  do
    files=`echo "$1" | sed 's/ /\?/g'`
    filesall="$files $filesall"
    shift
  done
killall vgmplay &
mate-terminal -e vgmplay $filesall&
```
do someone know what is going on there?

and previously, it was complaining about a missing .ini file - why wasn’t that .ini file automatically created when it was found missing?

thanks in advance! :)

**Comment by ValleyBell** [comment]
I don't have any experience with caja scripts, but there are a few things you should know:
1. VGMPlay takes only one argument, i.e. you can make it play either 1 file or 1 playlist.  
If you would want to play multiple VGM files, you'd have to create a .m3u playlist with all files and tell VGMPlay to play that.
2. VGMPlay never writes the .ini file - it only reads it. (and if it can't, it falls back to default values)  
If you do "make install" it should install the .ini file to a place where VGMPlay can find it.

Actually, looking at the [mate-terminal manpage](https://www.mankier.com/1/mate-terminal) - shouldn't you use `-x` instead of `-e`? Alternatively put the command in quotes.

**Comment by nitrofurano** [comment]
yes, it’s working fine with `-x`, thanks!!! :)
(btw, caja is a fork from nautilus, i don’t know if nautilus still supports scripts)
