### ISSUE TITLE
use NEZplug++ emulation core for Gameboy instead of MAME

### ISSUE THREAD

**Issue by djmaximum17** [vgmrips/vgmplay#75]
it would be nice if in the next release of VGMplay, Gameboy should use NEZplug++ emulation core. much like how the NES Famicom uses NSFplay. http://offgao.net/program/nezplug++.html

**Comment by superctr** [comment]
Please post this issue in the libvgm repo.

Since we plan to replace the current VGMPlay codebase, we have stopped working on new features like porting cores for the "legacy" VGMPlay in order to focus on libvgm instead.

Pull requests would still be OK (and appreciated) though.

**Comment by ValleyBell** [comment]
Is the NEZplug GameBoy core any better than the current MAME GameBoy core?

I know that GameBoy sound emulation used to be pretty bad for MAME 0.180 and earlier.
But since then it got completely rewritten and to me it seems to be pretty accurate now. (A tad *too* accurate, actually, as it emulates some waveform corruption bugs that are present on the original GameBoy, but not on the GameBoy Color.)

**Comment by djmaximum17** [comment]
yes, its sound emulation is actually pretty accurate
