### ISSUE TITLE
Error openning Sound Device!

### ISSUE THREAD

**Issue by nPHYN1T3** [vgmrips/vgmplay#88]
Can't get vgmplay to play anything. It will read the data from files and give you used chips, channels, game name etc but always finishes off with "Error openning Sound Device!"

I've tried tons of different files, building from git and the aur...same same. I can't find anything on how to set or pass args to denote the output device or subsystem.

**Comment by ValleyBell** [comment]
Sorry, but this version of VGMPlay requires you to select the sound subsystem at compile time.
It can do OSS or libao only. The latter can be enabled via https://github.com/vgmrips/vgmplay/blob/master/VGMPlay/Makefile#L37.

If you want something more flexible, you will have to compile https://github.com/ValleyBell/vgmplay-libvgm. (It is more complicated to build due to it being library + UI application, but it supports ALSA and PulseAudio as well.)

**Comment by nPHYN1T3** [comment]
I tried building vgmplay-libvgm too but it would stall and die due to ssl issues on the git clone. Trying again today to see if there was just some temporary shenanigans going on.

**Comment by ValleyBell** [comment]
If you have trouble using the git submodule, you can just `git clone` the libvgm repo into a different folder.

vgmplay-libvgm currently requires you to build libvgm separately first anyway. It is not "integrated" into its build process.
